site_name: stories

site_url: https://potykion.github.io/stories/
site_dir: site

theme:
  name: material
  features:
    - navigation.tabs
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      # Делает обычные ссылки кликабельными (не надо обрамлять в []())
  - pymdownx.magiclink

plugins:
  - search
  - awesome-nav
  - blog


